/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import { GlobalComponents } from 'vue'

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    Button: typeof import('primevue/button')['default']
    Card: typeof import('primevue/card')['default']
    Column: typeof import('primevue/column')['default']
    DataTable: typeof import('primevue/datatable')['default']
    DatePicker: typeof import('primevue/datepicker')['default']
    DefaultTable: typeof import('./src/components/DefaultTable.vue')['default']
    DevBar: typeof import('./src/components/DevBar.vue')['default']
    Dialog: typeof import('primevue/dialog')['default']
    DialogGroundSetting: typeof import('./src/components/Dialogs/DialogGroundSetting.vue')['default']
    DialogIncomingAlert: typeof import('./src/components/Dialogs/DialogIncomingAlert.vue')['default']
    DialogMessage: typeof import('./src/components/Dialogs/DialogMessage.vue')['default']
    DialogMessageIcon: typeof import('./src/components/Dialogs/DialogMessageIcon.vue')['default']
    DialogSiteStyle: typeof import('./src/components/Dialogs/DialogSiteStyle.vue')['default']
    DialogVersion: typeof import('./src/components/Dialogs/DialogVersion.vue')['default']
    FloatLabel: typeof import('primevue/floatlabel')['default']
    IconField: typeof import('primevue/iconfield')['default']
    InputIcon: typeof import('primevue/inputicon')['default']
    InputNumber: typeof import('primevue/inputnumber')['default']
    InputText: typeof import('primevue/inputtext')['default']
    Message: typeof import('primevue/message')['default']
    MessageError: typeof import('./src/components/MessageError.vue')['default']
    MultiSelect: typeof import('primevue/multiselect')['default']
    NavigationTabs: typeof import('./src/components/NavigationTabs.vue')['default']
    ProgressBar: typeof import('primevue/progressbar')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SectionFive: typeof import('./src/components/Dashbaord/SectionFive.vue')['default']
    SectionFour: typeof import('./src/components/Dashbaord/SectionFour.vue')['default']
    SectionOne: typeof import('./src/components/Dashbaord/SectionOne.vue')['default']
    SectionThree: typeof import('./src/components/Dashbaord/SectionThree.vue')['default']
    SectionTwo: typeof import('./src/components/Dashbaord/SectionTwo.vue')['default']
    Select: typeof import('primevue/select')['default']
    Tab: typeof import('primevue/tab')['default']
    TabList: typeof import('primevue/tablist')['default']
    Tabs: typeof import('primevue/tabs')['default']
    Textarea: typeof import('primevue/textarea')['default']
    Toast: typeof import('primevue/toast')['default']
    ToggleButton: typeof import('primevue/togglebutton')['default']
  }
  export interface GlobalDirectives {
    Ripple: typeof import('primevue/ripple')['default']
    Tooltip: typeof import('primevue/tooltip')['default']
  }
}

// For TSX support
declare global {
  const Button: typeof import('primevue/button')['default']
  const Card: typeof import('primevue/card')['default']
  const Column: typeof import('primevue/column')['default']
  const DataTable: typeof import('primevue/datatable')['default']
  const DatePicker: typeof import('primevue/datepicker')['default']
  const DefaultTable: typeof import('./src/components/DefaultTable.vue')['default']
  const DevBar: typeof import('./src/components/DevBar.vue')['default']
  const Dialog: typeof import('primevue/dialog')['default']
  const DialogGroundSetting: typeof import('./src/components/Dialogs/DialogGroundSetting.vue')['default']
  const DialogIncomingAlert: typeof import('./src/components/Dialogs/DialogIncomingAlert.vue')['default']
  const DialogMessage: typeof import('./src/components/Dialogs/DialogMessage.vue')['default']
  const DialogMessageIcon: typeof import('./src/components/Dialogs/DialogMessageIcon.vue')['default']
  const DialogSiteStyle: typeof import('./src/components/Dialogs/DialogSiteStyle.vue')['default']
  const DialogVersion: typeof import('./src/components/Dialogs/DialogVersion.vue')['default']
  const FloatLabel: typeof import('primevue/floatlabel')['default']
  const IconField: typeof import('primevue/iconfield')['default']
  const InputIcon: typeof import('primevue/inputicon')['default']
  const InputNumber: typeof import('primevue/inputnumber')['default']
  const InputText: typeof import('primevue/inputtext')['default']
  const Message: typeof import('primevue/message')['default']
  const MessageError: typeof import('./src/components/MessageError.vue')['default']
  const MultiSelect: typeof import('primevue/multiselect')['default']
  const NavigationTabs: typeof import('./src/components/NavigationTabs.vue')['default']
  const ProgressBar: typeof import('primevue/progressbar')['default']
  const RouterLink: typeof import('vue-router')['RouterLink']
  const RouterView: typeof import('vue-router')['RouterView']
  const SectionFive: typeof import('./src/components/Dashbaord/SectionFive.vue')['default']
  const SectionFour: typeof import('./src/components/Dashbaord/SectionFour.vue')['default']
  const SectionOne: typeof import('./src/components/Dashbaord/SectionOne.vue')['default']
  const SectionThree: typeof import('./src/components/Dashbaord/SectionThree.vue')['default']
  const SectionTwo: typeof import('./src/components/Dashbaord/SectionTwo.vue')['default']
  const Select: typeof import('primevue/select')['default']
  const Tab: typeof import('primevue/tab')['default']
  const TabList: typeof import('primevue/tablist')['default']
  const Tabs: typeof import('primevue/tabs')['default']
  const Textarea: typeof import('primevue/textarea')['default']
  const Toast: typeof import('primevue/toast')['default']
  const ToggleButton: typeof import('primevue/togglebutton')['default']
}